### ISSUE TITLE
Doing update instead of insert when Model::create()

### ISSUE THREAD

**Issue by hulloanson** [DenchikBY/Phalcon-MongoDB-ODM#10]
When I used `Model::create()`, specifying _id uses the updateOne function in MongoDB driver, which leads to silent failure if the _id does not exist in the collection.

To me, this is kind of counter-intuitive. The method is named 'create'. It should mean inserting a new record. What if I want to use a specific type, e.g. incremental integer, as primary key? Seems there's no choice for users.

I'd suggest separating create and update action.

**Comment by DenchikBY** [comment]
Model::create() method insert new record with passed fields.
MongoDB don't support autoincrement primaries like mysql
