### ISSUE TITLE
Database Error handling

### ISSUE THREAD

**Issue by hulloanson** [DenchikBY/Phalcon-MongoDB-ODM#11]
What I see is, If something's gone wrong during queries/inserts/updates when database error occurs (e.g. trying to update non-existent row), things just fails silently.

Printing some sort of stacktrace or even error code would be nice! It's quite hard to debug when something unexpected occurs.

Please point out if I'm wrong. Thanks.

**Comment by DenchikBY** [comment]
If something's gone wrong necessarily exception will thrown, you should wrap your code with try/catch
