### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by alexge233** [DenchikBY/Phalcon-MongoDB-ODM#14]
Hi, just run into your library, and seeing that Phalcon still doesn't support the new MongoDB driver, I gave it a try. Sadly, I've run into the following exception, I'm not doing anything other than follow the example to set it up (e.g., the model class, and the setting of the `$db` in the `index.php`, e.g.:

```php
$di->set('config', function () {
    return new \Phalcon\Config([
        'mongodb' => [
            'host' => 'localhost',
            'port' => 27017,
            'database' => 'pithea'
        ]
    ]);
}, true);

$di->set('mongo', function () {
    $config = $this->get('config')->mongodb;
    $manager = new \MongoDB\Driver\Manager('mongodb://' . $config->host . ':' . $config->port);
    return $manager;
}, true);
```
And my model (`app/models/Prices.php`);

```php
require __DIR__ . '/vendor/autoload.php';

use DenchikBY\MongoDB\Model;

class Prices extends Model
{
    public $symbol;
    public $data;

    public function initialize()
    {
        $this->setSource("prices");
    }
}
````

And the view controller:

```php
    public function pricesAction()
    {
        $this->view->pick('ajax/prices');
        $items = Prices::find();
        echo "There are ", count($items), "\n";
    }
```

Regardless of what I try, I keep getting:

```bash
PHP Fatal error:  Uncaught Error: Using $this when not in object context in app/models/vendor/denchikby/phalcon-mongodb-odm/src/MongoDB/Model.php:74
```

Any chance this can be fixed?

**Comment by kristoftorfs** [comment]
This is simply faulty code. Closures don't have a $this context (as is stated in the error message). You need to import the dependency injector into your closure as you can see below.

```php
$di->set('mongo', function () use ($di) {
    $config = $di->get('config')->mongodb;
    $manager = new \MongoDB\Driver\Manager('mongodb://' . $config->host . ':' . $config->port);
    return $manager;
}, true);
```

**Comment by alexge233** [comment]
@kristoftorfs thanks a lot for the reply, much appreciated!
This does solve the exception, however I'm a bit confused.
I am obviously using the wrong syntax (I was doing `Prices::find`) so just a quick question,
how do I search in my collection and retrieve the data?

Many thanks!
