### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by khachin** [DenchikBY/Phalcon-MongoDB-ODM#6]
MongoDB\Model.php line 26

$model = (new static(Di::getDefault()->get('mongo'), static::getDbName() . '.' . static::getSource()));

should be

$model = (new static(Di::getDefault()->get('mongo'), static::getDbName(), static::getSource()));

**Comment by DenchikBY** [comment]
[Fixed](https://github.com/DenchikBY/Phalcon-MongoDB-ODM/commit/36afa80c0e036d05e87bd667c1d081b8bdaedd3c)
